app/user/forms.py
# app/admin/forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

from ..models import Task

class TaskForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    description = StringField('Description', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/user/__init__.py
# app/user/__init__.py

from flask import Blueprint

user = Blueprint('user', __name__)

from . import views

app/user/views.py
# app/home/views.py

from flask import abort, flash, redirect, render_template, url_for
from flask_login import current_user, login_required

from . import user
from .forms import TaskForm
from .. import db
from ..models import Task


# Task Views
@user.route('/tasks', methods=['GET', 'POST'])
@login_required
def list_tasks():

    tasks = Task.query.all()
    curr_usr = current_user
    return render_template('user/tasks/tasks.html',
                           tasks=tasks, title="Tasks",
                           curr_usr=curr_usr)


@user.route('/tasks/add', methods=['GET', 'POST'])
@login_required
def add_task():

    add_task = True
    form = TaskForm()
    if form.validate_on_submit():
        task = Task(title=form.title.data,
                    description=form.description.data,
                    user_id=current_user.id)
        try:
            db.session.add(task)
            db.session.commit()
            flash('You have successfully added a new task.')
        except:
            abort(401)
        return redirect(url_for('user.list_tasks'))

    return render_template('user/tasks/task.html', action="Add",
                           add_task=add_task, form=form,
                           title="Add Task")

@user.route('/tasks/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_task(id):
    add_task = False

    task = Task.query.get_or_404(id)
    form = TaskForm(obj=task)
    
    if form.validate_on_submit():
        task.title = form.title.data
        task.description = form.description.data
        db.session.commit()
        flash('You have successfully edited the task.')

        return redirect(url_for('user.list_tasks'))

    form.description.data = task.description
    form.title.data = task.title
    return render_template('user/tasks/task.html', action="Edit",
                           add_task=add_task, form=form,
                           task=task, title="Edit Task")


@user.route('/tasks/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_task(id):

    task = Task.query.get_or_404(id)
    db.session.delete(task)
    db.session.commit()
    flash('You have successfully deleted the task.')

    return redirect(url_for('user.list_tasks'))
    return render_template(title="Delete Task")

app/templates/user/tasks/task.html
<!-- app/templates/admin/departments/department.html -->

{% import "bootstrap/wtf.html" as wtf %}
{% extends "base.html" %}
{% block title %}
    {% if add_task %}
        Add Department
    {% else %}
        Edit Department
    {% endif %}
{% endblock %}
{% block body %}
<div class="content-section">
 <div class="outer">
    <div class="middle">
      <div class="inner">
        <div class="center">
            {% if add_task %}
                <h1>Add Department</h1>
            {% else %}
                <h1>Edit Department</h1>
            {% endif %}
            <br/>
            {{ wtf.quick_form(form) }}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/user/tasks/tasks.html
<!-- app/templates/admin/tasks/tasks.html -->

{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}Tasks{% endblock %}
{% block body %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Tasks</h1>
        {% if tasks %}

        <div class="container">
          <div class="row">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th scope="col">Title</th>
                  <th scope="col">Description</th>
                  <th scope="col">Created By</th>
                  <th scope="col">Edit</th>
                  <th scope="col">Delete</th>
                </tr>
              </thead>
              <tbody>
                      {% for task in tasks %}
                        <tr>
                          <td> {{ task.title }} </td>
                          <td> {{ task.description }} </td>
                          <td>
                            {% if task.get_user() %}
                              {{ task.get_user().first_name }} {{ task.get_user().last_name }}
                            {% else %}
                              Unknown?
                            {% endif %}
                          </td>
                          {% if curr_usr.is_admin or curr_usr.id == task.user_id %}
                          <td>
                            <a href="{{ url_for('user.edit_task', id=task.id) }}" class="btn btn-warning btn-lg">
                              <i class="fa fa-pencil"></i> Edit 
                            </a>
                          </td>
                          <td>
                            <a href="{{ url_for('user.delete_task', id=task.id) }}" class="btn btn-danger btn-lg">
                              <i class="fa fa-trash"></i> Delete 
                            </a>
                          </td>
                          {% else %}
                          <td style="background-color: #aec251; color: white;">
                              Forbidden 
                          </td>
                          <td style="background-color: #aec251; color: white;">
                              Forbidden
                          </td>
                          {% endif %}

                        </tr>
                      {% endfor %}
              </tbody>
            </table> 
          </div>
        </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No tasks have been added. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="{{ url_for('user.add_task') }}" class="btn btn-primary btn-lg">
            <i class="fa fa-plus"></i>
            Add Task
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}